# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
ENV["VERSION_NUMBER"] = "3.17.0"

platform :ios do
  desc "Description of what the lane does"
  lane :buildNo do
	# add actions here: https://docs.fastlane.tools/actions
	buildNo = 1
	lastGitTag = last_git_tag()

	if lastGitTag != nil
		buildNo = lastGitTag.scan(/((\S+))/).last.first.gsub("(", "").gsub(")", "").to_i + 1
	end

	newGitTag = "v" + ENV["VERSION_NUMBER"] + "(" + buildNo.to_s + ")" 
	add_git_tag(
		tag: newGitTag
	)
	push_git_tags()
  end
end
